name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows-static-md
          - os: macos-latest
            triplet: x64-osx

    env:
      VCPKG_DEFAULT_TRIPLET: ${{matrix.triplet}}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@main
        with:
          buildDirectory: ${{github.workspace}}/build
          vcpkgGitCommitId: 1323f4b83d6a91e415e9ce06a45c9d0a6473aaf2
          runVcpkgInstall: true
          appendedCacheKey: vcpkg

      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-vcpkg'
          buildPreset: 'ninja-vcpkg'
          testPreset: 'ninja-vcpkg'
