name: PR-Checks

on: [pull_request]

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt install libboost-thread-dev libopus-dev libprotobuf-dev
      shell: bash

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Check line endings
      uses: erclu/check-crlf@v1

    - name: Generate compile-command DB
      run: mkdir build; cd build; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..; cd ..; ln -s build/compile_commands.json .
      shell: bash

    - name: Check code formatting
      uses: jidicula/clang-format-action@v4.10.2
      with:
          clang-format-version: '10'
          check-path: '.'
          exclude-regex: '(build/.*|_dependencies/.*)'
          include-regex: '.*\.(cpp|hpp|c|h)$'
